name: slide_puzzle
description: A slide puzzle game for Flutter Puzzle Hack

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  adaptive_theme: ^2.3.0
  async_task: ^1.0.17
  cached_network_image: ^3.2.0
  collection:
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  font_awesome_flutter: ^9.2.0
  go_router: ^3.0.1
  google_fonts: ^2.1.0
  hexagon: ^0.2.0-nullsafety.1
  http: ^0.13.4
  image_picker: ^0.8.4+6
  intl: ^0.17.0
  js: ^0.6.3
  just_audio: ^0.9.18
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  test:
  url_launcher: ^6.0.17

dev_dependencies:
  cupertino_icons: ^1.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic

